### DISCUSSION TITLE
Compile problem with sea-query-binder

### DISCUSSION THREAD

**Discussion by k3dom** [SeaQL/sea-query#819] [Q&A]
Hello, I have been trying to get sea-query-binder with sqlx to work but I am facing a issue with `sqlx::query_as_with`.
This is the code in question:
```rust
let (sql, values) = Query::select()
            .column(Asterisk)
            .from(Courses::Table)
            .cond_where(Expr::col(Courses::Id).eq(a.course_id))
            .build_sqlx(PostgresQueryBuilder);

        let course = sqlx::query_as_with::<_, Course, _>(&sql, values)
            .fetch_one(&pool)
            .await?;
```

But I get the following error.
```
error[E0277]: the trait bound `SqlxValues: IntoArguments<'_, _>` is not satisfied
   --> src/routes/application.rs:50:64
    |
50  |         let course = sqlx::query_as_with::<_, Course, _>(&sql, values)
    |                      -----------------------------------       ^^^^^^ the trait `IntoArguments<'_, _>` is not implemented for `SqlxValues`
    |                      |
    |                      required by a bound introduced by this call
    |
    = help: the following other types implement trait `IntoArguments<'q, DB>`:
              <AnyArguments<'q> as IntoArguments<'q, <AnyArguments<'q> as sqlx::Arguments<'q>>::Database>>
              <PgArguments as IntoArguments<'q, <PgArguments as sqlx::Arguments<'q>>::Database>>
              <sqlx_core::arguments::ImmutableArguments<'q, DB> as IntoArguments<'q, DB>>
note: required by a bound in `sqlx::query_as_with`
   --> /home/kedom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/query_as.rs:363:8
    |
360 | pub fn query_as_with<'q, DB, O, A>(sql: &'q str, arguments: A) -> QueryAs<'q, DB, O, A>
    |        ------------- required by a bound in this function
...
363 |     A: IntoArguments<'q, DB>,
    |        ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `query_as_with`

```

This is confusing to be because I am using the `sea-query-binder` crate which, looking at the source, provides this exact trait implementation. I also added the `sqlx-postgres` feature which should enable it. Here is my `Cargo.toml`:
```toml
[package]
...

[dependencies]
dotenvy = "0.15.7"
anyhow = "1.0.88"

axum = { version = "0.7.5", features = ["tracing", "json"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["trace"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
chrono = { version = "0.4.38", features = ["serde"] }

sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "derive",
    "migrate",
]}
sea-query = { version = "0.31.0", features = [
    "derive",
    "attr",
    "backend-postgres",
]}
sea-query-binder = { version = "0.6.0", features = ["sqlx-postgres"] }

[[bin]]
...
```

Here are both the `Iden` enum and the struct that I am trying to cast my row into:
```rust
use serde::Serialize;

#[derive(sqlx::FromRow, Serialize)]
pub struct Course {
    id: i32,
    name: String
}

#[derive(Iden)]
pub enum Courses {
    Table,
    Id,
}
```

Id be awesome if anybody could help me out here.
