### ISSUE TITLE
sea-query-rusqlite - rusqlite 0.30 is not supported by sea-query-rusqlite version 0.4

### ISSUE THREAD

**Issue by jeremychone** [SeaQL/sea-query#726]
Here are the typos fixed:

## Description

`rusqlite 0.30` is not supported by `sea-query-rusqlite 0.4`

## Steps to Reproduce

1. Cargo.toml

```toml
sea-query = "0.30"
sea-query-rusqlite = "0.4"
rusqlite = { version = "0.30", features = ["bundled"] }
```

3. Will fail to compile because `sea-query-rusqlite` bundles `rusqlite 0.29`.

4. `rusqlite = "0.30"` without the bundled feature will fail as well.

### Expected Behavior

Should compile with the latest `rusqlite`

### Actual Behavior

Fails to compile when `rusqlite = "0.30"` but works when `rusqlite = "0.29"`.

### Reproduces How Often

Always reproducible.

## Versions

```
sea-query = "0.30"
sea-query-rusqlite = "0.4"
```
